# Generated by Django 3.0.3 on 2020-09-02 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'image_types',
            },
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'main_categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=4096, null=True)),
                ('style', models.CharField(max_length=32)),
                ('retali_price', models.IntegerField(null=True)),
                ('colorway', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ReleaseDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'release_dates',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'sizes',
            },
        ),
        migrations.CreateModel(
            name='SizeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'size_types',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.MainCategory')),
            ],
            options={
                'db_table': 'sub_categories',
            },
        ),
        migrations.CreateModel(
            name='Specific',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.SubCategory')),
            ],
            options={
                'db_table': 'specifics',
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Size')),
            ],
            options={
                'db_table': 'product_sizes',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Specific'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_size',
            field=models.ManyToManyField(related_name='product_with_size', through='product.ProductSize', to='product.Size'),
        ),
        migrations.AddField(
            model_name='product',
            name='release_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ReleaseDate'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.SizeType'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=4096)),
                ('image_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ImageType')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_with_product', to='product.Product')),
            ],
            options={
                'db_table': 'images',
            },
        ),
    ]
